# Site settings
title: 'import_wrapper : easy imports for cBioPortal'
email: stuart@morungos.com
description: > # this means to ignore newlines until "baseurl:"
  Designed to make it easy to add stuff into cBioPortal
baseurl: "/import_wrapper/" # the subpath of your site, e.g. /blog/
url: "http://pughlab.github.io" # the base hostname & protocol for your site
twitter_username: morungos
github_username:  morungos
name: 'import_wrapper'
tagline: 'easy imports for cBioPortal'

# Build settings
markdown: kramdown
